version: '3.0'
services:
  telegram_sticker_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STICKER_SAVE_HOST_PATH}:/app/files/
      - ${CONFIG_FILE_HOST_PATH}:/app/config.json